In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
vec1=np.array(my_list)

In [4]:
type(vec1)

numpy.ndarray

In [5]:
vec1.shape

(3,)

In [6]:
m_list=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
mat1=np.array(m_list)

In [8]:
type(m_list)

list

In [9]:
mat1.shape

(3, 3)

In [10]:
np.array(m_list).shape

(3, 3)

In [12]:
np.arange(0,10)    #creates a vector of nubers from 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)     #creates a vector of nmbrs frm 0 to 11 stepping by 2

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)   #creates row of zeros from the speciefied nmbrs

array([0., 0., 0.])

In [16]:
np.zeros((3,3))  #creates the Matrix of zeros from the specified parameters

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.ones((3,3)*2)

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [21]:
np.ones((3,3))*2   #there is no

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [22]:
np.linespace(0,10,5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [24]:
np.eye(4)           #for IDENTITY matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(10)     #gives random specified numbers

array([0.06706962, 0.35905474, 0.62171415, 0.86224542, 0.07621553,
       0.93061175, 0.57932306, 0.60206714, 0.03431777, 0.53645033])

In [28]:
np.random.rand(5,5)

array([[0.4919668 , 0.86734082, 0.0221617 , 0.5017946 , 0.55456389],
       [0.3366485 , 0.08590713, 0.10167221, 0.21025856, 0.8251811 ],
       [0.07704156, 0.54589177, 0.13801318, 0.37778372, 0.24206373],
       [0.60431048, 0.13822474, 0.74794595, 0.36189932, 0.94870088],
       [0.227326  , 0.40204321, 0.93906508, 0.07519349, 0.96642182]])

In [31]:
np.random.randint(1,100)     #to get a random nummber from the specified range

72

In [33]:
np.random.randint(1,100,10)    #it will give a specified number of values within the range

array([43, 37, 75, 24,  4, 28, 84, 13, 87, 73])

In [40]:
arr1 = np.arange(25)

In [37]:
arr=np.random.randint(0,50,10)

In [42]:
print(arr)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
