In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv('Data.csv')

In [3]:
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
  #In 

In [5]:
X=ds.iloc[:,:-1].values             # [.values] converts the data into an Numpy array

In [6]:
Y=ds.iloc[:,3:].values              # For Y axis i.e. dependent variable it is mandatory to convert it into numpy arrays

In [7]:
 # ML algo takes the data in numpy format, for cnvrtng the extracted data we have used [.values]      
 # In most of the cases X and Y are expected to be in numpy array.

In [8]:
#Taking care of missing values

In [9]:
from sklearn.preprocessing import Imputer   

                                            # sklearn is a Library within that preprocessing is a package 
                                            # and within that Imputer is a class

In [10]:
imputer = Imputer(missing_values = 'NaN' , strategy='mean' , axis=0)  

# Imputer Class is used to fill the missing values.
 # strategy is how we want to fill the missing values, and axis is loc of col.

In [11]:
imputer = imputer.fit(X[: , 1:3])   # location of where to fill the data.

In [12]:
X[: , 1:3] = imputer.transform(X[ : , 1:3])      # We have to use Transform method to fill the missing values.

In [13]:
type(X)

numpy.ndarray

In [14]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
# Encoding categorical data
# Encoding the Independent Variable

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
                            
    
    #In sklearn there is another classes that are used to encode the String columns into numerical column. 

In [17]:
# Use Label Encoding to label the categorical column and then use OneHotEncoder to change the labeled format to array format.
# Here converting into labelEncoding, it will treat the first column as 0,1,2 
# and it will compare it as 0<1<2 or france < spain < germany, we dont want this here
# so for this we have used OneHotEncoder, it will convert these 0,1,2 into an array and it will add 3 columns to the dataset.

In [18]:
labelencoder_X = LabelEncoder()

In [19]:
X[: , 0] = labelencoder_X.fit_transform(X[: , 0])    #the method fit_transform will convert the given column into 0,1,2 format.

In [20]:

onehotencoder = OneHotEncoder(categorical_features = [0])   # This will convert the data into array format, 
                                                            # We can use more columns if we have more categorical columns.

In [21]:
X =onehotencoder.fit_transform(X).toarray() 

#This will fit the data into the dataset as an array and add 3 columns respectively.

In [22]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [23]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [24]:
# Encoding the dependent variable

# Do not apply OneHotEncoding to your dependent variable if it is a categorical value, only apply LabelEncoding.
  # Because it is designed like this,it will interprete your data correctly.

In [25]:
Y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [26]:
labelencoder_Y = LabelEncoder()
Y=labelencoder_Y.fit_transform(Y)      #this will convert it into 0,1 format

C:\Users\Arbaz\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [28]:
#Train_test_split

In [29]:
from sklearn.cross_validation import train_test_split

C:\Users\Arbaz\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [31]:
# In sklearn there is cross_validation inside that there is train_test_split class which is used to train and split the data.
# train_test_split takes parameter as 1) X (independent variable)  2) Y (dependent variable) 3) test_size
# the test size is  the size we want to give for testing, if we want to give 20% of data for testing we give as test_size = 0.2

In [32]:
X_train, X_test, Y_train, Y_test

(array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
         5.80000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
         6.37777778e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
         6.70000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
         7.20000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
         5.20000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
         6.10000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
         7.90000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
         4.80000000e+04]]),
 array([[0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
        [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04]]),
 array([1, 1, 1, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 0], dtype=int64))