In [1]:
pwd

'C:\\Users\\Arbaz'

In [2]:
print(pwd)

NameError: name 'pwd' is not defined

In [3]:
clear

In [4]:
import numpy as np

In [5]:
arr=np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [9]:
arr[1:5]                  #it will give values from 1 to 5 index values  (get values in a range)

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [14]:
arr[0:5]=100         #BROADCASTING    (setting a value with index range)

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))            #creating a 2D array

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[1,0]                  #getting numbers from indexing (the parameters are index of rows and colums)

20

In [26]:
arr_2d[:2,1:]                       #slicing the array  #shaping the array to (2,2 order from the right corner) #(beginning of the colm:end of the colom)

array([[10, 15],
       [25, 30]])

In [27]:
arr_2d[1]

array([20, 25, 30])

In [31]:
arr_2d[]

SyntaxError: invalid syntax (<ipython-input-31-bd717b714743>, line 1)

In [32]:
arr_2d[0:1]

array([[ 5, 10, 15]])

In [33]:
arr_2d[0:,1:2]

array([[10],
       [25],
       [40]])

In [34]:
arr_2d[2,:]

array([35, 40, 45])

In [45]:
arr_2d[1,:2]

array([20, 25])

In [39]:
arr=np.arange[1,11]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [40]:
arr=np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr=np.arange(0,10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr+arr                                #addition of arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
arr-arr                                #substraction of arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr*arr                                #multiplication of arrays

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [54]:
arr/arr                                 #division of arrays

C:\Users\Arbaz\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
arr*2                                  #multiplying array with a number

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
arr**3                                #gives the cube of each number in the array

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [ ]:
         #core python will not support the above operations, it can only be done in numpy or pandas


In [59]:
#ex    
l1=[1,2]
l2=[2,3]
l1+l2                         #it will not add elements but instead it appends the elements in the list

[1, 2, 2, 3]

In [60]:
np.sqrt(arr)                                          #it will give the square root of each element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
np.exp(arr)                               #it will calculate the exponential of elements (e^)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [64]:
np.max(arr)           #it will give the maximum number from the array

9