In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Position_Salaries.csv')

In [3]:
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [11]:
x = df.iloc[:,1:-1].values

In [24]:
y =df.iloc[:,2:].values


C:\Users\Arbaz\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [22]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [23]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]], dtype=int64)

In [25]:
from sklearn.cross_validation import train_test_split 

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2)

In [27]:
X_train

array([[ 3],
       [ 5],
       [ 1],
       [ 8],
       [ 6],
       [ 9],
       [ 7],
       [10]], dtype=int64)

In [28]:
X_test

array([[4],
       [2]], dtype=int64)

In [29]:
Y_train

array([[  60000],
       [ 110000],
       [  45000],
       [ 300000],
       [ 150000],
       [ 500000],
       [ 200000],
       [1000000]], dtype=int64)

In [30]:
Y_test

array([[80000],
       [50000]], dtype=int64)

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lm = LinearRegression()

In [33]:
lm.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [34]:
Y_predict = lm.predict(X_test)

In [35]:
Y_predict

array([[115818.88246628],
       [-53410.40462428]])

In [44]:
# Mean_absolute_method

In [36]:
from sklearn import metrics

In [37]:
print('MAE :', metrics.mean_absolute_error(Y_test,Y_predict))

MAE : 69614.64354527938


In [38]:
np.mean(Y_test)

65000.0

In [41]:
69614.64354527938/65000.0

1.0709945160812213

In [43]:
 # R-Square method

In [42]:
lm.score(X_test, Y_test)

-25.61489805708902